<?php 
	$button = Mage::getModel('kubitoo_webrtc/configuration')->getAvailableButtons(); 

	if(count($button) > 0 ):
?>


<a href="javascript:window.open('https://client.kubitoo.com/index.php?tokenid=<?php echo $button->getFirstItem()->getTokenid(); ?>','LiveSupport','width=450, height=450, directories=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=no');void(0);" class="btn_kubitoo">
	<span><?php echo $button->getFirstItem()->getTextbutton(); ?></span>
</a>

<?php echo $button->getFirstItem()->getHtmlbutton(); ?>


<?php endif; ?>